languageCode = "ja-jp"
title = "Kwappa研究開発室"
googleAnalytics = "UA-20517132-1"
enableEmoji = true

[params]
author = "kwappa"
description = "randd.kwappa.net"
baseURL = "https://randd.kwappa.net/"
avatar = "/images/kwappa_icon.jpeg"
customCSS = ["/css/custom-style.css"]
favicon = "/favicons/"
myLinks = [
    { "name" = "list", "url" = "/", "text" = "Articels" },
    { "name" = "book", "url" = "/publishing" },
    { "name" = "home", "url" = "https://kwappa.net"},
]
socialLinks = [
    { "name" = "github", "url" = "https://github.com/kwappa" },
    { "name" = "twitter", "url" = "https://twitter.com/kwappa" },
    { "name" = "facebook", "url" = "https://facebook.com/kwappa" },
]
[[social]]
    twitter = "kwappa"

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true
