languageCode = "ja-jp"
title = "Kwappa研究開発室"
enableEmoji = true
baseURL = "https://randd.kwappa.net/"

[services]
    [services.googleAnalytics]
        ID = 'G-07G58K1CKC'

[params]
author = "kwappa"
description = "randd.kwappa.net"
avatar = "/images/kwappa_icon_full.png"
customCSS = ["/css/custom-style.css"]
favicon = "/favicons/"
[params.social]
    twitter = "kwappa"
[[params.myLinks]]
    name = "list"
    url = "/"
[[params.myLinks]]
    name = "book"
    url = "/publishing"
[[params.myLinks]]
    name = "home"
    url = "https://kwappa.net"
[[params.socialLinks]]
    name = "github"
    url = "https://github.com/kwappa"
[[params.socialLinks]]
    name = "twitter"
    url = "https://twitter.com/kwappa"
[[params.socialLinks]]
    name = "facebook"
    url = "https://facebook.com/kwappa"

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true
